### PR TITLE
Rename NodeRelation.schema_name -> NodeRelation.schema

### LINKED ISSUE #106: Rename the 'schema_name' field on node_relation to simply 'schema'
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward change to existing dbt-semantic-interfaces functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Rename the 'schema_name' field on node_relation to simply 'schema'

### Describe alternatives you've considered

_No response_

### Who will this benefit?

_No response_

### Are you interested in contributing this feature?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by peterallenwebb**
Resolves #106 

### Description

Rename NodeRelation.schema_name -> NodeRelation.schema

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Review by QMalcolm — APPROVED** [review]
Looks good to me

**Comment by QMalcolm** [comment]
Woof so I took a look at the CI errors, and it looks like the issue is that `schema` is a property that pydantics `BaseModel` adds to classes 🙃 That complicates things

**Comment by peterallenwebb** [comment]
We probably just discovered why it was schema_name in the first place. I'll figure out what our options are.

**Comment by peterallenwebb** [comment]
Abandoned for a different approach using an alias.

**Pull request closed without merging**
