### PR TITLE
Renaming Measure Proxy to Simple

### LINKED ISSUE #7: [CT-2353][Epic] Initial build out of new package `dbt-semantic-interfaces` for sharing of semantic layer interfaces
As noted in https://github.com/dbt-labs/dbt-core/discussions/7456, for the integration of dbt-core and MetricFlow we are creating a third repo to put the shared semantic interface defintions. This is that repo. What that entails is protocol definitions for the semantic interfaces, default object implementations, default parsing / transformations / validations, and associated tests.

```[tasklist]
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/1
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/2
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/8
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/9
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/10
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/11
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/12
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/13
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/14
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/15
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/16
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/17
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/18
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/19
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/20
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/21
```

```[tasklist]
# Right Now Refactors
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/48
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/49
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/50
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/30
```

```[tasklist]
# Public Alpha Refactors
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/51
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/53
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/54
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/55
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/67
```

```[tasklist]
# Public Beta Refactors
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/56
- [ ] https://github.com/dbt-labs/dbt-semantic-interfaces/issues/57
```

### LINKED ISSUE #48: [Spec Update] Rename `measure_proxy` metric type to `simple`
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward change to existing dbt-semantic-interfaces functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Measure proxy isn't going to make as much sense in the new world of simple metrics & derived metrics. So let's rename it to simple!

### Describe alternatives you've considered

_No response_

### Who will this benefit?

_No response_

### Are you interested in contributing this feature?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by callum-mcdata**
resolves #48 

### Description

As part of the `Right Now` set of changes in issue #7, renaming measure proxy to simple.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by QMalcolm** [comment]
I'll clean up this PR's history on Monday

**Comment by Jstein77** [comment]
Hype! Thanks @QMalcolm. I can update docs to reflect the renaming once this is merged.

**Comment by QMalcolm** [comment]
@tlento & @Jstein77 Aside from the code changes, how do we feel about this direction? Is `simple` the right name?

**Review by tlento — APPROVED** [review]
I'm good with the name, let's just double check with @nhandel before merge.

**Comment by QMalcolm** [comment]
Closing in favor of #80

**Pull request closed without merging**
