### PR TITLE
Migrated jsonschema.RefResolver to referencing.Registry

### LINKED ISSUE #135: [Feature] Allow jsonschema 4 as dependency
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward change to existing dbt-semantic-interfaces functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I wanted to install dbt-core together with Airflow 2.6.3, using their [constraints file](https://raw.githubusercontent.com/apache/airflow/constraints-2.6.3/constraints-3.10.txt). However the pinned usage of jsonschema 3 in this project prevented me from this, as the constraints require version 4:
```
The conflict is caused by:
    apache-airflow[amazon,cncf-kubernetes,statsd] 2.6.3 depends on jsonschema>=4.0.0
    flask-appbuilder 4.3.1 depends on jsonschema<5 and >=3
    apache-airflow 2.6.3 depends on jsonschema>=4.0.0
    connexion[flask] 2.14.2 depends on jsonschema<5 and >=2.5.1
    dbt-semantic-interfaces 0.2.0 depends on jsonschema~=3.0
    The user requested (constraint) jsonschema==4.18.0
```

jsonschema 4 has been out for ~2 years and this project is quite new, so I don't know why it's relying on old software.

### Describe alternatives you've considered

_No response_

### Who will this benefit?

_No response_

### Are you interested in contributing this feature?

yes

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by codecae**
Resolves #135

### Description

Migrate from jsonschema.RefResolver to referencing.Registry in support of jsonschema 4 upgrade

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by codecae** [comment]
```
Successfully installed anyio-4.0.0 black-23.9.1 certifi-2023.7.22 cfgv-3.4.0 distlib-0.3.7 execnet-2.0.2 filelock-3.12.4 h11-0.14.0 httpcore-0.18.0 httpx-0.25.0 identify-2.5.29 idna-3.4 iniconfig-2.0.0 isort-5.12.0 mypy-1.5.1 mypy-extensions-1.0.0 nodeenv-1.8.0 packaging-23.1 pathspec-0.11.2 platformdirs-3.10.0 pluggy-1.3.0 pre-commit-3.4.0 pytest-7.4.2 pytest-xdist-3.3.1 ruff-0.0.260 sniffio-1.3.0 types-Jinja2-2.11.9 types-MarkupSafe-1.1.10 types-PyYAML-6.0.12.12 types-jsonschema-4.19.0.3 types-python-dateutil-2.8.19.14 virtualenv-20.24.5
Finished syncing dependencies
cmd [1] | pytest -n auto tests
================================================================================ test session starts ================================================================================
platform linux -- Python 3.11.4, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/codec/git/dbt-semantic-interfaces
plugins: anyio-4.0.0, xdist-3.3.1
8 workers [133 items]   
.....................................................................s..........................................s....................                                         [100%]
========================================================================== 131 passed, 2 skipped in 2.41s ===========================================================================
```

**Comment by codecae** [comment]
I have signed the CLA but the workflow seems to be stuck.  Anything I need to do on my end?

**Comment by QMalcolm** [comment]
> I have signed the CLA but the workflow seems to be stuck. Anything I need to do on my end?

I was looking at our list of people who've signed the CLA, and I do see you in there as `@codecae`. For whatever reason if the submitted `GitHub Account Name` has an `@` at the start, it gets dropped. I'm going to see if I'm allowed to manually edit our list of github account names that have signed the CLA. You may need to sign the CLA again though and use `codecae` for the `GitHub Account Name` field instead of `@codecae`

**Comment by codecae** [comment]
I wondered if that might be the issue.  I figured it was looking for what the CLA bot posted in the automated to comment

**Comment by QMalcolm** [comment]
@codecae I'll see about getting the CLA bot message to be more clear! It probably puts the `@` in the message to notify the specific users, but that seems confusing without some level of clarification 🙃 Additionally, apparently "bad things happen"™️ when we manually edit the list of people who've signed the CLA, so resigning it is probably the best way forward

**Comment by codecae** [comment]
I just signed it all again and it seemed to work just fine 👍

**Comment by codecae** [comment]
Should be squeaky clean now... linter seems happy.

**Comment by codecae** [comment]
Would you prefer a squash to lower the noise floor a bit on the commit history?

**Comment by QMalcolm** [comment]
> Would you prefer a squash to lower the noise floor a bit on the commit history?

Yea we'll probably end up squash merging, just to keep the history clear of cleanup commits

**Comment by codecae** [comment]
I ran the linter in containers for 3.8-3.11 I *think* everything should be good now.  Sorry for the small misses here.

**Comment by QMalcolm** [comment]
> I ran the linter in containers for 3.8-3.11 I _think_ everything should be good now. Sorry for the small misses here.

No worries! The number of times the linter has caught me is too many to count. Thank you for sticking with it, this work is incredibly helpful 🙂

**Review by QMalcolm — APPROVED** [review]
Thank you again for doing this work! This looks great 🚀

**Comment by zli06160** [comment]
Super quick reaction! Thank you 🍾

**Comment by codecae** [comment]
> Thank you again for doing this work! This looks great 🚀

Glad to help!

**Pull request merged**
