### PR TITLE
Rename `SavedQuery.group_bys` to `SavedQuery.group_by`

### LINKED ISSUE #192: [Bug] Rename `SavedQuery.group_bys` to `SavedQuery.group_by`
### Is this a new bug in dbt-semantic-interfaces?

- [X] I believe this is a new bug in dbt-semantic-interfaces
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In the Github issue describing the saved query feature (https://github.com/dbt-labs/metricflow/issues/765), there was a typo in the `group_bys` field - the author mentioned that it was supposed to be `group_by`.

### Expected Behavior

`SavedQuery.group_bys` should be `SavedQuery.group_by`.

### Steps To Reproduce

N/A

### Relevant log output

_No response_

### Environment

```markdown
- OS: N/A
- Python: N/A
- dbt: N/A
- dbt-semantic-interfaces: 0.3
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by plypaul**
Resolves #192 

### Description

Please see associated issue for more details.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-semantic-interfaces/blob/main/CONTRIBUTING.md#adding-a-changelog-entry)

### CODE REVIEW

**Comment by plypaul** [comment]
@QMalcolm - How do we go about handling this kind of rename on the `dbt-core` side?

**Comment by QMalcolm** [comment]
> @QMalcolm - How do we go about handling this kind of rename on the `dbt-core` side?

We can't, at least not for dbt-core 1.7, and that is a for a few reasons

- dbt-core 1.7 will depend on DSI 0.3.x, and we can't backport this to 0.3.latest because it's breaking
- dbt-core handles this via detecting manifest schema versions. Only 1 schema exists per dbt-core minor version
  - group_bys was introduced in 1.7.0rc1, thus there is no schema migration path for this property in core 1.7.latest

The only way to do this currently for dbt-core 1.7.0 and DSI 0.3.0 would be to support both, which also seems undesireable

**Comment by QMalcolm** [comment]
We'll put this into 0.4.0 and then jam that into the final cut of dbt-core 1.7.0

**Review by QMalcolm — APPROVED** [review]
Looks good to me!

**Comment by plypaul** [comment]
@QMalcolm - Good point, created an issue in DSI and updated links.

**Pull request merged**
